version: "3.8"

services:
  api:
    build: .

    restart: on-failure
    # noinspection ComposeUnknownValues
    ports:
      - "9191:8080"


    volumes:
      - .m2:/root/.m2
      - .:/workdir/server/src
      - ./src/main/resources/application.yml:/workdir/server/src/main/resources/application.yml
    stdin_open: true
    tty: true

