kind: PersistentVolume
apiVersion: v1
metadata:
  name: "{{ .Values.pv.name }}"
  labels:
    type: local
    app: "{{ .Values.deployments.postgres.service.name }}"
spec:
  storageClassName: "standard"
  capacity:
    storage: "{{ .Values.pv.size }}"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.pvc.name }}"
  labels:
    app: "{{ .Values.deployments.postgres.service.name }}"
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.pvc.size }}"
