apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}-pgadmin
  labels:
    app:  {{ .Release.Name }}-pgadmin
spec:
  selector:
    app:  {{ .Release.Name }}-pgadmin
  type: NodePort
  ports:
    - port: 80
      nodePort: 30200
