apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
          - name: {{ .Release.Name }}-postgres-container
            image: postgres:latest
            env:
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-postgres-root-password
                    key: password
              - name: POSTGRES_DB
                value: {{ .Values.postgres.databaseName }}
              #              - name: postgres_USER
              #                valueFrom:
              #                  secretKeyRef:
              #                    name: {{ .Release.Name }}-postgres-username
              #                    key: username
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-postgres-username
                    key: username
            ports:
              - containerPort: 5433
            volumeMounts:
              - name: {{ .Release.Name }}-postgres-persistent-storage
                mountPath: {{ .Values.postgresVolume.mountPath }}
      volumes:
        - name: {{ .Release.Name }}-postgres-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgres-pvc