apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-service-signature-app-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-service-signature-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-service-signature-app
    spec:
      containers:
        - name: {{ .Release.Name }}-service-signature-app
          image: {{ .Values.springApp.image.repository }}:{{ .Values.springApp.image.tag }}
          imagePullPolicy: {{ .Values.springApp.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ include "my-spring-app.fullPostgresConnectionURL" . | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-username
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-password
                  key: password
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: "org.hibernate.dialect.PostgreSQLDialect"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "eureka-0"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-0.eureka.default.svc.cluster.local:8761/eureka"
            - name: SPRING_APPLICATION_NAME  # New environment variable for Spring application name
              value: "service-signature"  # Set your desired Spring application name here

