#spring:
#  application:
#    name: scraping
#server:
#  port: 8080
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://great_carver:8761/eureka}
#  instance:
#    preferIpAddress: true
spring:
  kafka:
    bootstrap-servers: my-cluster-kafka-bootstrap:9092