replicaCount: 1

postgres:
  databaseName: documents_db

springApp:
  image:
    repository: ilyeszaidi/service-document-app
    pullPolicy: IfNotPresent
    tag: latest

postgresVolume:
  persistentVolumeClaim:
    storageSize: 200Mi  #1Gi

  persistentVolume:
    storageSize: 200Mi  #1Gi
    pathOnHost: /var/lib/postgres  # Replace this with the actual path on your host machine


  mountPath: /var/lib/postgres