apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-root-password
type: Opaque
stringData:
  password: '123456'

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-username
type: Opaque
stringData:
  username: postgres

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-password
type: Opaque
stringData:
  password: '123456'

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pgadmin-secret
type: Opaque
data:
  pgadmin-default-password: bXlwd2Q=